image: rikorose/gcc-cmake:gcc-9

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y libboost-filesystem-dev
  script: 
    - mkdir -p cmake-build
    - cd cmake-build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
    - cmake-build/*
    expire_in: 1 week

test:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y libboost-filesystem-dev
  script:
    - cd cmake-build
    - rm -fr ../test/configurations/*/results*
    - ctest --output-on-failure
  artifacts:
    paths:
    - cmake-build/*
    expire_in: 1 week
